db.driver=com.mysql.cj.jdbc.Driver

db.url=${DB_URL}
db.username=${DB_USER}
db.password=${DB_PASS}
# HIBERNATE CONFIG
# =========================
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
hibernate.jdbc.time_zone=UTC

# =========================
# GMAIL CONFIG
# =========================
mail.imap.host=imap.gmail.com
mail.imap.port=993
mail.imap.protocol=imaps
mail.imap.folder=INBOX
mail.imap.connectionTimeout=10000
mail.imap.timeout=15000
mail.scheduler.fixedDelayMillis=300000
mail.initial.fetch.count=50

# =========================
# APP SETTINGS
# =========================
app.urgent.threshold=70